### ISSUE TITLE
Georefes - Búsqueda de establecimientos cercanos

### ISSUE THREAD

**Issue by leogit81** [leogit81/grupo421#37]
Al realizar la búsqueda de establecimientos cercanos se encuentra un error por consola para IE:

SCRIPT438: Object doesn't support property or method 'remove'
File: BaseCollectionView.js, Line: 77, Column: 17
SCRIPT438: Object doesn't support property or method 'remove'
File: BaseCollectionView.js, Line: 77, Column: 17

En Chrome funciona, puede ser un problema de compatibilidad entre browser y que IE no esté soportando esta función. Cargo el error porque puede generar problemas en WP8.
Es probable que lo mismo esté sucediendo para la búsqueda de farmacias y droguerías cercanas. Habría que probarlo también para estas consultas.
![georefes1](https://cloud.githubusercontent.com/assets/7827349/5952755/67f867e4-a75c-11e4-8f1b-5fa5fc4316b0.png)
![georefes2](https://cloud.githubusercontent.com/assets/7827349/5952756/6c88baf2-a75c-11e4-876d-d236a46a7fa7.png)

Ver capturas de pantalla.

**Comment by leogit81** [comment]
Al ser un error en la BaseCollectionView.js, está sucediendo en varios lugares. También lo detecte en la búsqueda de referentes.

**Comment by lucasr28** [comment]
Arreglado
