### ISSUE TITLE
Error recarga del mapa en Georefes

### ISSUE THREAD

**Issue by nicochaikh** [leogit81/grupo421#38]
Luego de hacer una consulta de establecimientos en georefes, y acceder a algun establecimiento desde el mapa para ver su consulta nominal, al ver el establecimiento en mapa (desde la consulta de establecimiento nominal que se abre) y volver al mapa de georefes, este se desarma todo como se ve en la imagen. Simplemente con cambiar a la lista y volver a la vista de mapa se soluciona. Debería alcanzar con agregar algún refresh.

![screenshot_2015-02-21-11-26-46](https://cloud.githubusercontent.com/assets/8091656/6314439/ca9cde34-b9bd-11e4-99f1-5cdd4796e043.png)

**Comment by lucasr28** [comment]
Arreglado
